In [4]:
# w-net torch leftover

import torch
import torchvision as tv
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torchvision.utils import save_image


In [2]:
# Extract multiple outputs from network
"""
out1, out2 = model(data)
loss1 = criterion1(out1, target1)
loss2 = criterion2(out2, target2)
loss = loss1 + loss2
loss.backward()
"""


'\nout1, out2 = model(data)\nloss1 = criterion1(out1, target1)\nloss2 = criterion2(out2, target2)\nloss = loss1 + loss2\nloss.backward()\n'

In [ ]:
import numpy as np
A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A.data)
_A = A.view(1, -1)
print(_A.data)
_B = _A.expand(9,-1)
print(_B.data)
__B = _B.repeat(9,9)
print(__B.data)
__A = A.reshape(-1).repeat(1,3)
print(__A)
#_A = A.view(-1,1).expand(3,3).reshape(-1)
#_B = B.repeat(3)
#torch.stack([_A, _B])

In [ ]:
A = torch.tensor([[[1,1,1],[2,2,2],[3,3,3]],
                  [[1,2,3],[1,2,3],[1,2,3]]])
#A.unsqueeze_(-1)
#A.expand(-1,-1,9,-1)

H = 3
W = 4
a = torch.zeros(H,W,H*W,dtype=torch.float)
for i in range(H):
    a[i, :, :] = i
b = torch.zeros(H,W,H*W, dtype = torch.float)
for j in range(H):
    b[:,:,W*j:W*(j+1)] = j
    
print(a.size())
print(a.data[:,:,0])
print(b.size())

c = a - b
c = torch.mul(c,c)
print(c.data[:,:,0])

#assume we have f
f = c.clone()
c = c + f

sigma_x_squared = 16
c = torch.exp(-torch.div(c, sigma_x_squared))



c = torch.norm(c,p=2, dim=1)
print(c.size())


#a = torch.randn(64, 10, 3, 32, 32)
#a = a.view(64, -1)
#b = torch.norm(a, p=2, dim=1)
#torch.sum(b)



In [ ]:
#print(a)
b = a.data[:,:,0].clone()
print(b)
print(b.size())

c = torch.zeros(3,4,2)
d = b.data.clone()
d.unsqueeze_(-1)
d = d.reshape(1,1,-1)
print(d.size())
print(d.data)
d = d.expand(3,4,-1)
print(d.size())
print(b.data)
print(d.data[:,:,0])
print(d.data[:,:,4])
assert(d.size() ==torch.Size([3,4,12]))
print("--------")
d = d.sum(dim = 2)
print(d.size())
#print(d.size())

In [6]:
a = torch.zeros(2,3,4)
print(a)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [11]:
a[:,:,0:-1:2] = 1
print(a)
print(a.size())

tensor([[[1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.]],

        [[1., 0., 1., 0.],
         [1., 0., 1., 0.],
         [1., 0., 1., 0.]]])
torch.Size([2, 3, 4])


In [19]:
b = torch.zeros(2,3)

In [20]:
print(b)
print(b.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [45]:
import time
st = time.time()
a = torch.arange(end = 48, dtype=torch.float, requires_grad=True ).cuda()
a.unsqueeze_(-1)
a = a.expand(-1, 80)
a.unsqueeze_(-1)
a = a.expand(-1,-1,48*80)
print(time.time() - st)

b = torch.zeros(48,80,48*80, dtype=torch.float, requires_grad=True).cuda()
st = time.time()
for i in range(48):
    b[i,:,:] = i
print(time.time() - st)

0.001081705093383789
0.0040361881256103516


In [46]:
print(a[:,:,0])

tensor([[ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  ...,  2.,  2.,  2.],
        ...,
        [45., 45., 45.,  ..., 45., 45., 45.],
        [46., 46., 46.,  ..., 46., 46., 46.],
        [47., 47., 47.,  ..., 47., 47., 47.]], device='cuda:0',
       grad_fn=<SelectBackward>)


In [47]:
print(b[:,:,0])

tensor([[ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  ...,  2.,  2.,  2.],
        ...,
        [45., 45., 45.,  ..., 45., 45., 45.],
        [46., 46., 46.,  ..., 46., 46., 46.],
        [47., 47., 47.,  ..., 47., 47., 47.]], device='cuda:0',
       grad_fn=<SelectBackward>)


In [40]:
print(a.size())
print(b.size())

torch.Size([48, 80, 3840])
torch.Size([48, 80, 3840])


In [75]:
st = time.time()
a = torch.arange(end = 48, dtype = torch.float, requires_grad = True).cuda()
a.unsqueeze_(-1)
a = a.expand(-1,80)
#a.permute(1,0)
a.unsqueeze_(-1)
a = a.reshape(1,1,-1)
a = a.expand(48,80,-1)
print(time.time() - st)


0.0012977123260498047


In [76]:
H = 48
W = 80
st = time.time()
a = torch.arange(end = H, dtype = torch.float, requires_grad = True).cuda()
a = a.repeat_interleave(W)
a.unsqueeze_(-1)
a.unsqueeze_(-1)
a = a.permute(1,2,0)
a = a.expand(H,W,-1)
print(time.time() - st)

0.0015690326690673828


In [77]:
print(a.size())
print(a[:,:,79])

torch.Size([48, 80, 3840])
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0',
       grad_fn=<SelectBackward>)


In [64]:
st = time.time()
H = 48
W = 80
a = torch.arange(end = W, dtype=torch.float, requires_grad=True ).cuda()
a.unsqueeze_(-1)
a = a.expand(-1, H)
a = a.permute(1,0)
a.unsqueeze_(-1)
a = a.expand(-1,-1,48*80)
print(time.time() - st)

0.001340627670288086


In [65]:
print(a.size())
print(a[:,:,0])

torch.Size([48, 80, 3840])
tensor([[ 0.,  1.,  2.,  ..., 77., 78., 79.],
        [ 0.,  1.,  2.,  ..., 77., 78., 79.],
        [ 0.,  1.,  2.,  ..., 77., 78., 79.],
        ...,
        [ 0.,  1.,  2.,  ..., 77., 78., 79.],
        [ 0.,  1.,  2.,  ..., 77., 78., 79.],
        [ 0.,  1.,  2.,  ..., 77., 78., 79.]], device='cuda:0',
       grad_fn=<SelectBackward>)


In [85]:
H = 48
W = 80
st = time.time()

a = torch.arange(end = W, dtype = torch.float, requires_grad = True).cuda()
a = a.repeat(H)
#a.permute(1,0)
a.unsqueeze_(-1)
a.unsqueeze_(-1)
a = a.permute(1,2,0)
a = a.expand(H,W,-1)
print(time.time() - st)

0.0011401176452636719


In [88]:
print(a.size())
print(a[:,:,1])

torch.Size([48, 80, 3840])
tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], device='cuda:0',
       grad_fn=<SelectBackward>)


In [82]:
print(a)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9])


In [ ]:
self.u_enc1 = nn.Sequential(
            nn.Conv2d(self.input_channels, 16, kernel_size=3, padding = (1,1)),
            nn.ReLU(True),
            nn.Conv2d(16,16,kernel_size=3, padding = (1,1)),
            nn.ReLU(True))

In [12]:
import torch
a = torch.tensor([[1,2,3,4],[5,6,7,8]])
a.unsqueeze_(0)
a = a.expand(5,-1,-1)
print(a.size())

torch.Size([5, 2, 4])


In [13]:
print(a[0,:,:])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [14]:
a = a.sum((1,2))

In [15]:
a.size()

torch.Size([5])

In [19]:
a = torch.tensor([1,2,3])
b = torch.tensor([2,3,4])

a *= b

print(a)

tensor([ 2,  6, 12])


In [ ]:
def calculate_denom():
     """
    ### Before Optimization
    seg = segmented_slice.data.clone()
    H,W = seg.size()
    seg.unsqueeze_(-1)
    seg = seg.expand(-1,-1, H*W)
    assert(seg.size() == torch.Size([H,W,H*W]))
    assert(weight_matrix.size() == torch.Size([H,W,H*W]))
    seg = torch.mul(seg, weight_matrix)
    return seg.sum()
    """
    pass

def calculate_num():
    pass

def calculate_weight_matrix():
    """    
    r_slice = original_img.data[:,0,:,:].clone()
    g_slice = original_img.data[:,1,:,:].clone()
    b_slice = original_img.data[:,2,:,:].clone()
    
    r_matrix1 = r_slice.data.clone()
    r_matrix1.unsqueeze_(-1)
    r_matrix1.expand(-1,-1,-1,H*W) #N,H,W,H*W
    assert(r_matrix1.size() == torch.Size([N,H,W,H*W]))
    r_matrix2 = r_slice.data.clone()
    r_matrix2.unsqueeze_(-1)
    r_matrix2 = r_matrix2.reshape(N, 1, 1, -1) #N,1,1,H*W
    r_matrix2 = r_matrix2.expand(-1, H, W, -1) #N,H,W,H*W
    assert(r_matrix2.size() == torch.Size([N, H, W, H*W]))
    r = r_matrix1 - r_matrix2
    r = torch.mul(r,r)
    
    g_matrix1 = g_slice.data.clone()
    g_matrix1.unsqueeze_(-1)
    g_matrix1.expand(-1, -1,-1,H*W)
    g_matrix2 = g_slice.data.clone()
    g_matrix2.unsqueeze_(-1)
    g_matrix2 = g_matrix2.reshape(N, 1, 1, -1)
    g_matrix2 = g_matrix2.expand(-1, H, W, -1)
    assert(g_matrix2.size() == torch.Size([N, H, W, H*W]))
    g = g_matrix1 - g_matrix2
    g = torch.mul(g,g)
    
    b_matrix1 = b_slice.data.clone()
    b_matrix1.unsqueeze_(-1)
    b_matrix1.expand(-1, -1,-1,H*W)
    b_matrix2 = b_slice.data.clone()
    b_matrix2.unsqueeze_(-1)
    b_matrix2 = b_matrix2.reshape(N, 1, 1, -1)
    b_matrix2 = b_matrix2.expand(-1, H, W, -1)
    assert(b_matrix2.size() == torch.Size([N, H, W, H*W]))
    b = b_matrix1 - b_matrix2
    b = torch.mul(b,b)
    
    pixel_diff = torch.exp( -torch.div(r+g+b, sigma_i_squared) )
    weight = torch.mul(pixel_diff, dist_diff)
    assert(weight.size() == torch.Size([H,W,H*W]))
    return weight
    """
    pass


In [60]:
import torch
import torchvision as tv
import torchvision.transforms as transforms
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from torchvision.utils import save_image

import gc
gc.collect()

import os
torch.cuda.empty_cache() 
os.environ["CUDA_VISIBLE_DEVICES"]="0"
torch.cuda.set_device(0)

In [83]:
def custom_loss(y_hat, y, z):
    #assume z is given from different function
    #assume y_hat and y have the same size
    
    zz = z.clone()
    
    yy = y.clone()
    yy = yy - z
    yy = y_hat - yy
    return yy.sum()
    
def custom_loss1(y_hat, y, z):
    #assume z is given from different function
    #assume y_hat and y have the same size
    
    yy = torch.tensor(y.clone(), requires_grad = True)
    yy = yy - z
    yy = y_hat - yy
    return yy.sum()

In [75]:
class custom_model(torch.nn.Module):
    def __init__(self):
        super(custom_model,self).__init__()
        self.build()
    
    def forward(self, x):
        return self.u_enc1111(x)
        
        
    def build(self):
        self.u_enc1111 = nn.Sequential()
        self.u_enc1111.add_module('Conv1_1', nn.Conv2d(3, 16, kernel_size=3, padding = (1,1)))
        self.u_enc1111.add_module('Relu1_2', nn.ReLU(True))
        self.u_enc1111.add_module('Conv1_3', nn.Conv2d(16,3,kernel_size=3, padding = (1,1)))
        self.u_enc1111.add_module('Relu1_4', nn.ReLU(True))
        self.u_enc1111.add_module('Soft1_5', nn.Softmax())

In [93]:
model = custom_model().cuda()
distance = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=10000, momentum=0.9)

In [94]:
N = 10
C = 3
H = 40
W = 40

imgs = Variable(torch.randn(N,C,H,W)).cuda()
#dist_diff_matrix = Variable(torch.randn(H,W), requires_grad = True).cuda()
dist_diff_matrix = torch.randn(H,W).cuda()
dist_diff_matrix.unsqueeze_(0)
dist_diff_matrix.unsqueeze_(0)
dist_diff_matrix = dist_diff_matrix.expand(N,C, -1, -1)



output = model(imgs)

print("before zero_grad call")
print(model.u_enc1111.Conv1_1.weight[0,:,:,:])
grad = model.u_enc1111.Conv1_1.weight.grad
if grad is not None:
    print(grad[0,:,:,:])
else:
    print(grad)
print("----------------------------")


optimizer.zero_grad()
loss1 = custom_loss1(output, imgs, dist_diff_matrix)
#loss1 = Variable(loss1, requires_grad = True)
loss1.backward()
#loss2 = distance(output, dist_diff_matrix)
#loss2.backward()

print("after zero call and after backward")
print(model.u_enc1111.Conv1_1.weight[0,:,:,:])
grad = model.u_enc1111.Conv1_1.weight.grad
if grad is not None:
    print(grad[0,:,:,:])
else:
    print(grad)
print("----------------------------")

optimizer.step()

print("after step")
print(model.u_enc1111.Conv1_1.weight[0,:,:,:])
grad = model.u_enc1111.Conv1_1.weight.grad
if grad is not None:
    print(grad[0,:,:,:])
else:
    print (grad)

print("----------------------------")

optimizer.zero_grad()
print(model.u_enc1111.Conv1_1.weight[0,:,:,:])
grad = model.u_enc1111.Conv1_1.weight.grad
print("after zero call")
if grad is not None:
    print(grad[0,:,:,:])
else:
    print (grad)

print("----------------------------")

before zero_grad call
tensor([[[ 0.1284,  0.0036, -0.1598],
         [ 0.1199,  0.0864, -0.0357],
         [ 0.0580, -0.0695,  0.0806]],

        [[ 0.1184,  0.0902, -0.0552],
         [ 0.0232,  0.0981,  0.1567],
         [-0.1375, -0.1377,  0.0428]],

        [[ 0.0326,  0.0029, -0.0108],
         [ 0.1170,  0.0442, -0.0877],
         [ 0.0808,  0.0051, -0.0389]]], device='cuda:0',
       grad_fn=<SliceBackward>)
None
----------------------------
after zero call and after backward
tensor([[[ 0.1284,  0.0036, -0.1598],
         [ 0.1199,  0.0864, -0.0357],
         [ 0.0580, -0.0695,  0.0806]],

        [[ 0.1184,  0.0902, -0.0552],
         [ 0.0232,  0.0981,  0.1567],
         [-0.1375, -0.1377,  0.0428]],

        [[ 0.0326,  0.0029, -0.0108],
         [ 0.1170,  0.0442, -0.0877],
         [ 0.0808,  0.0051, -0.0389]]], device='cuda:0',
       grad_fn=<SliceBackward>)
tensor([[[ 9.6356e-07,  1.7768e-08, -7.1210e-07],
         [ 5.9666e-07,  3.5531e-07, -4.8494e-08],
         [ 4.17

/nethome/jbang36/anaconda3/envs/eva_37/lib/python3.7/site-packages/ipykernel_launcher.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [40]:
for name, param in model.named_parameters():
    print (param.grad)
    break

None


In [51]:
print(model.u_enc1.Conv1_1.weight[0,:,:,:])

tensor([[[ 0.0560, -0.1330, -0.0267],
         [-0.1872,  0.1331,  0.0186],
         [-0.1645,  0.0920, -0.1450]],

        [[-0.0766, -0.0321,  0.1303],
         [ 0.0745, -0.0829, -0.0746],
         [ 0.0668, -0.0384, -0.0322]],

        [[ 0.1757,  0.0651, -0.0474],
         [-0.0561, -0.0633,  0.1458],
         [ 0.0536, -0.0451,  0.1067]]], device='cuda:0',
       grad_fn=<SliceBackward>)


In [48]:
print(model.u_enc1)

Sequential(
  (Conv1_1): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (Relu1_2): ReLU(inplace)
  (Conv1_3): Conv2d(16, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (Relu1_4): ReLU(inplace)
  (Soft1_5): Softmax()
)


In [95]:
a = torch.tensor([[1,2,3],[4,5,6]])

In [96]:
b = a
b.unsqueeze_(-1)
print(b.size())
c = a
c.unsqueeze_(-1)
print(c.size())

torch.Size([2, 3, 1])
torch.Size([2, 3, 1, 1])


In [115]:

def calculate_dist_matrix(N, H, W):
    
    sigma_x_squared = 16
    #x_matrix1 = torch.arange(end = H, dtype=torch.float, requires_grad=True).cuda()
    x_matrix1 = torch.arange(end = H, dtype=torch.float).cuda()
    
    x_matrix1.unsqueeze_(-1)
    x_matrix1 = x_matrix1.expand(-1, W)
    x_matrix1.unsqueeze_(-1)
    x_matrix1 = x_matrix1.expand(-1,-1,H*W)
    
    
    #x_matrix2 = torch.arange(end = H, dtype = torch.float, requires_grad = True).cuda()
    x_matrix2 = torch.arange(end = H, dtype = torch.float).cuda()
    x_matrix2.unsqueeze_(-1)
    x_matrix2 = x_matrix2.expand(-1,W)
    x_matrix2.unsqueeze_(-1)
    x_matrix2 = x_matrix2.reshape(1,1,-1)
    x_matrix2 = x_matrix2.expand(H,W,-1)
    
    
    x_matrix1 = x_matrix1 - x_matrix2
    print("h_matrix")
    for i in range(H*W):
        print(x_matrix1[:,:,i])
    print("--------------")
    
    x_matrix1 = torch.pow(x_matrix1, 2)
    
    
    
    #y_matrix1 = torch.arange(end = W, dtype=torch.float, requires_grad=True ).cuda()
    y_matrix1 = torch.arange(end = W, dtype=torch.float).cuda()
    y_matrix1.unsqueeze_(-1)
    y_matrix1 = y_matrix1.expand(-1, H)
    y_matrix1 = y_matrix1.permute(1,0)
    y_matrix1.unsqueeze_(-1)
    y_matrix1 = y_matrix1.expand(-1,-1,H*W)
    
    #y_matrix2 = torch.arange(end = W, dtype = torch.float, requires_grad = True).cuda()
    y_matrix2 = torch.arange(end = W, dtype = torch.float).cuda()
    y_matrix2 = y_matrix2.repeat(H)
    y_matrix2.unsqueeze_(-1)
    y_matrix2.unsqueeze_(-1)
    y_matrix2 = y_matrix2.permute(1,2,0)
    y_matrix2 = y_matrix2.expand(H,W,-1)
    
    y_matrix1 = y_matrix1 - y_matrix2
    print("w_matrix")
    for i in range(H*W):
        print(y_matrix1[:,:,i])
    print("--------------")
    
    y_matrix1 = torch.pow(y_matrix1,2)
    
    tmp = x_matrix1 + y_matrix1
    
    print("h^2 + w^2 matrix")
    for i in range(H*W):
        print(tmp[:,:,i])
    print("--------------")
    
    
    dist_diff = torch.exp( -torch.div(x_matrix1+y_matrix1, sigma_x_squared) )
    assert(dist_diff.size() == torch.Size([H,W,H*W]))
    dist_diff.unsqueeze_(0)
    dist_diff = dist_diff.expand(N,-1, -1, -1) #N,H,W,H*W

    return dist_diff


In [116]:
N = 1
H = 2
W = 3
dist_matrix = calculate_dist_matrix(N,H,W)

print(dist_matrix[0,:,:,0])

h_matrix
tensor([[0., 0., 0.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0., 0., 0.],
        [1., 1., 1.]], device='cuda:0')
tensor([[0., 0., 0.],
        [1., 1., 1.]], device='cuda:0')
tensor([[-1., -1., -1.],
        [ 0.,  0.,  0.]], device='cuda:0')
tensor([[-1., -1., -1.],
        [ 0.,  0.,  0.]], device='cuda:0')
tensor([[-1., -1., -1.],
        [ 0.,  0.,  0.]], device='cuda:0')
--------------
w_matrix
tensor([[0., 1., 2.],
        [0., 1., 2.]], device='cuda:0')
tensor([[-1.,  0.,  1.],
        [-1.,  0.,  1.]], device='cuda:0')
tensor([[-2., -1.,  0.],
        [-2., -1.,  0.]], device='cuda:0')
tensor([[0., 1., 2.],
        [0., 1., 2.]], device='cuda:0')
tensor([[-1.,  0.,  1.],
        [-1.,  0.,  1.]], device='cuda:0')
tensor([[-2., -1.,  0.],
        [-2., -1.,  0.]], device='cuda:0')
--------------
h^2 + w^2 matrix
tensor([[0., 1., 4.],
        [1., 2., 5.]], device='cuda:0')
tensor([[1., 0., 1.],
        [2., 1., 2.]], device='cuda:0')
tensor([[4., 1., 0.],
   

In [120]:
def create_weight_matrix(N, H, W, K, dist_diff, original_img):
    # given the corresponding height and width, will create a weight matrix of size H,W,HxW according to the formula given in
    # w-net paper.
    # original_img size: torch.Size(N,C,H,W)
    # dist_diff size: torch.Size(N,H,W,H*W)
    # we will assume matrix of size H, W is given, it is initialized to zeros
    
    sigma_i_squared = 100
    r = 5
     
    #matrix1 = original_img
    #matrix1 = torch.tensor(original_img.clone(), requires_grad = True)
    matrix1 = original_img.clone()
    matrix1.unsqueeze_(-1)
    matrix1 = matrix1.expand(-1,-1,-1,-1,H*W)
    assert(matrix1.size() == torch.Size([N,C,H,W,H*W]))
    
    #matrix2 = torch.tensor(original_img.clone(), requires_grad = True)
    #matrix2 = original_img
    matrix2 = original_img.clone()
    matrix2.unsqueeze_(-1)
    matrix2 = matrix2.reshape(N,C,1,1,-1) #N,C,1,1,H*W
    matrix2 = matrix2.expand(-1,-1,H,W,-1) #N,C,H,W,H*W
    assert(matrix2.size() == torch.Size([N,C,H,W,H*W]))
    matrix1 = matrix1 - matrix2
    matrix1 = torch.pow(matrix1,2) #N,C,H,W,H*W
    
    matrix1 = torch.exp( -torch.div( matrix1.sum(1), sigma_i_squared) ) #N,H,W,H*W
    weight = torch.pow(matrix1, 2) #N,H,W,H*W
    assert(weight.size() == torch.Size([N,H,W,H*W]))
    weight.unsqueeze_(1)
    weight = weight.expand(-1,K,-1,-1,-1) #N,K,H,W,H*W
    
    return weight

In [126]:
torch.manual_seed(0)

rgb = torch.randn(3,2,3).cuda()
rgb.unsqueeze_(0)
print(rgb)
print(rgb.size())


tensor([[[[-1.1258, -1.1524,  0.5667],
          [ 0.7935,  0.5988, -1.5551]],

         [[-0.3414,  1.8530,  0.4681],
          [-0.1577, -0.1734,  0.1835]],

         [[ 1.3894,  1.5863,  0.9463],
          [-0.8437,  0.9318,  1.2590]]]], device='cuda:0')
torch.Size([1, 3, 2, 3])


In [127]:
K = 5
weight = create_weight_matrix(N,H,W,K, dist_matrix, rgb)

In [128]:
weight.size()

torch.Size([1, 5, 2, 3, 6])